### ISSUE TITLE
When building: "react-scripts: command not found"

### ISSUE THREAD

**Issue by paulcgt** [jackmatt2/koinly-chrome-extensions#1]
Hi there, 

Thanks for working on this project. I'm very new to npm, and this one has me stumped. Would you mind telling me what you think I could be doing wrong:

>[root@f313e733639b koinly-chrome-extensions]# npm run build
>
> koinly-chrome-extensions@0.1.0 build
> REACT_APP_ENVIRONMENT=development INLINE_RUNTIME_CHUNK=false react-scripts build
>
>sh: react-scripts: command not found
>[root@f313e733639b koinly-chrome-extensions]#

Thank you!
Paul

**Comment by jackmatt2** [comment]
HI,

You need to run `npm install` first - have updated the docs now.

You can also install via the Chrome Web Store now
https://chrome.google.com/webstore/detail/koinly-extensions/fjbemjajjdfpfccgbfblflhakhlilhpl
